// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHxFW4CHapOaPRo2OZcioCF3D10Gn_e2c',
    appId: '1:532660982994:web:52d85034337f32cf0b090b',
    messagingSenderId: '532660982994',
    projectId: 'flutter-6bfc9',
    authDomain: 'flutter-6bfc9.firebaseapp.com',
    storageBucket: 'flutter-6bfc9.firebasestorage.app',
    measurementId: 'G-D7B61F54NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQIwWfZjAgH0oi3gP-rps_yurx9u8youw',
    appId: '1:532660982994:android:39191db8fc94f8600b090b',
    messagingSenderId: '532660982994',
    projectId: 'flutter-6bfc9',
    storageBucket: 'flutter-6bfc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOkEexz2RAPOd-S9nZ9LElp9BIKCNaByY',
    appId: '1:532660982994:ios:75bbd6827757b7e70b090b',
    messagingSenderId: '532660982994',
    projectId: 'flutter-6bfc9',
    storageBucket: 'flutter-6bfc9.firebasestorage.app',
    iosClientId: '532660982994-7289c730uep3j6q01050etk77o52gf86.apps.googleusercontent.com',
    iosBundleId: 'com.example.ingilizceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOkEexz2RAPOd-S9nZ9LElp9BIKCNaByY',
    appId: '1:532660982994:ios:75bbd6827757b7e70b090b',
    messagingSenderId: '532660982994',
    projectId: 'flutter-6bfc9',
    storageBucket: 'flutter-6bfc9.firebasestorage.app',
    iosClientId: '532660982994-7289c730uep3j6q01050etk77o52gf86.apps.googleusercontent.com',
    iosBundleId: 'com.example.ingilizceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHxFW4CHapOaPRo2OZcioCF3D10Gn_e2c',
    appId: '1:532660982994:web:ef1b49e6083a528c0b090b',
    messagingSenderId: '532660982994',
    projectId: 'flutter-6bfc9',
    authDomain: 'flutter-6bfc9.firebaseapp.com',
    storageBucket: 'flutter-6bfc9.firebasestorage.app',
    measurementId: 'G-XF9W6H3DXE',
  );
}
