class WordsData {
  static const List<Map<String, String>> allWords = [
    // --- GRUP 1: TEMEL EŞYALAR VE FİİLLER (1-60) ---
    {"en": "Apple", "tr": "Elma"}, {"en": "Book", "tr": "Kitap"},
    {"en": "Cat", "tr": "Kedi"}, {"en": "Dog", "tr": "Köpek"},
    {"en": "Eat", "tr": "Yemek yemek"}, {"en": "Friend", "tr": "Arkadaş"},
    {"en": "Go", "tr": "Gitmek"}, {"en": "House", "tr": "Ev"},
    {"en": "Ice", "tr": "Buz"}, {"en": "Jump", "tr": "Zıplamak"},
    {"en": "Key", "tr": "Anahtar"}, {"en": "Love", "tr": "Sevmek"},
    {"en": "Moon", "tr": "Ay"}, {"en": "Name", "tr": "İsim"},
    {"en": "Orange", "tr": "Portakal"}, {"en": "Pen", "tr": "Kalem"},
    {"en": "Queen", "tr": "Kraliçe"}, {"en": "Red", "tr": "Kırmızı"},
    {"en": "Sun", "tr": "Güneş"}, {"en": "Tree", "tr": "Ağaç"},
    {"en": "Water", "tr": "Su"}, {"en": "Yellow", "tr": "Sarı"},
    {"en": "Door", "tr": "Kapı"}, {"en": "Window", "tr": "Pencere"},
    {"en": "Table", "tr": "Masa"}, {"en": "Chair", "tr": "Sandalye"},
    {"en": "Sleep", "tr": "Uyuma"}, {"en": "Run", "tr": "Koşmak"},
    {"en": "Drink", "tr": "İçmek"}, {"en": "Walk", "tr": "Yürümek"},
    {"en": "Read", "tr": "Okumak"}, {"en": "Write", "tr": "Yazmak"},
    {"en": "Listen", "tr": "Dinlemek"}, {"en": "Speak", "tr": "Konuşmak"},
    {"en": "Big", "tr": "Büyük"}, {"en": "Small", "tr": "Küçük"},
    {"en": "Happy", "tr": "Mutlu"}, {"en": "Sad", "tr": "Üzgün"},
    {"en": "Hot", "tr": "Sıcak"}, {"en": "Cold", "tr": "Soğuk"},
    {"en": "Good", "tr": "İyi"}, {"en": "Bad", "tr": "Kötü"},
    {"en": "Old", "tr": "Eski/Yaşlı"}, {"en": "New", "tr": "Yeni"},
    {"en": "Fast", "tr": "Hızlı"}, {"en": "Slow", "tr": "Yavaş"},
    {"en": "Early", "tr": "Erken"}, {"en": "Late", "tr": "Geç"},
    {"en": "Hard", "tr": "Zor/Sert"}, {"en": "Easy", "tr": "Kolay"},
    {"en": "Bread", "tr": "Ekmek"}, {"en": "Milk", "tr": "Süt"},
    {"en": "Egg", "tr": "Yumurta"}, {"en": "Cheese", "tr": "Peynir"},
    {"en": "Meat", "tr": "Et"}, {"en": "Fish", "tr": "Balık"},
    {"en": "Fruit", "tr": "Meyve"}, {"en": "Vegetable", "tr": "Sebze"},
    {"en": "City", "tr": "Şehir"}, {"en": "World", "tr": "Dünya"},

    // --- GRUP 2: ZAMAN VE MEKAN (61-120) ---
    {"en": "Time", "tr": "Zaman"}, {"en": "Day", "tr": "Gün"},
    {"en": "Week", "tr": "Hafta"}, {"en": "Month", "tr": "Ay"},
    {"en": "Year", "tr": "Yıl"}, {"en": "Today", "tr": "Bugün"},
    {"en": "Morning", "tr": "Sabah"}, {"en": "Night", "tr": "Gece"},
    {"en": "School", "tr": "Okul"}, {"en": "Work", "tr": "İş"},
    {"en": "Office", "tr": "Ofis"}, {"en": "Store", "tr": "Mağaza"},
    {"en": "Money", "tr": "Para"}, {"en": "Price", "tr": "Fiyat"},
    {"en": "Buy", "tr": "Satın almak"}, {"en": "Sell", "tr": "Satmak"},
    {"en": "Help", "tr": "Yardım etmek"}, {"en": "Play", "tr": "Oynamak"},
    {"en": "Watch", "tr": "İzlemek"}, {"en": "Find", "tr": "Bulmak"},
    {"en": "Keep", "tr": "Tutmak/Korumak"}, {"en": "Start", "tr": "Başlamak"},
    {"en": "Stop", "tr": "Durmak"}, {"en": "Wait", "tr": "Beklemek"},
    {"en": "Show", "tr": "Göstermek"}, {"en": "Try", "tr": "Denemek"},
    {"en": "Call", "tr": "Aramak/Çağırmak"}, {"en": "Ask", "tr": "Sormak"},
    {"en": "Answer", "tr": "Cevap vermek"}, {"en": "Believe", "tr": "İnanmak"},
    {"en": "Change", "tr": "Değiştirmek"}, {"en": "Choose", "tr": "Seçmek"},
    {"en": "Clean", "tr": "Temizlemek"}, {"en": "Close", "tr": "Kapatmak"},
    {"en": "Open", "tr": "Açmak"}, {"en": "Cook", "tr": "Yemek pişirmek"},
    {"en": "Dance", "tr": "Dans etmek"}, {"en": "Drive", "tr": "Sürmek"},
    {"en": "Feel", "tr": "Hissetmek"}, {"en": "Forget", "tr": "Unutmak"},
    {"en": "Remember", "tr": "Hatırlamak"}, {"en": "Give", "tr": "Vermek"},
    {"en": "Take", "tr": "Almak"}, {"en": "Bring", "tr": "Getirmek"},
    {"en": "Learn", "tr": "Öğrenmek"}, {"en": "Teach", "tr": "Öğretmek"},
    {"en": "Live", "tr": "Yaşamak"}, {"en": "Die", "tr": "Ölmek"},
    {"en": "Send", "tr": "Göndermek"}, {"en": "Receive", "tr": "Almak/Teslim almak"},
    {"en": "Pay", "tr": "Ödemek"}, {"en": "Cost", "tr": "Maliyet"},
    {"en": "Begin", "tr": "Başlamak"}, {"en": "Finish", "tr": "Bitirmek"},
    {"en": "Agree", "tr": "Anlaşmak"}, {"en": "Allow", "tr": "İzin vermek"},
    {"en": "Avoid", "tr": "Kaçınmak"}, {"en": "Build", "tr": "İnşa etmek"},
    {"en": "Care", "tr": "Önemsemek"}, {"en": "Carry", "tr": "Taşımak"},
    // --- GRUP 3 & 4: SIFATLAR, DUYGULAR VE SOSYAL YAŞAM (121-360) ---
    {"en": "Catch", "tr": "Yakalamak"}, {"en": "Check", "tr": "Kontrol etmek"}, {"en": "Clear", "tr": "Net/Temiz"}, {"en": "Collect", "tr": "Toplamak"},
    {"en": "Compare", "tr": "Karşılaştırmak"}, {"en": "Complain", "tr": "Şikayet etmek"}, {"en": "Complete", "tr": "Tamamlamak"}, {"en": "Confirm", "tr": "Onaylamak"},
    {"en": "Connect", "tr": "Bağlanmak"}, {"en": "Consider", "tr": "Düşünmek/Dikkate almak"}, {"en": "Continue", "tr": "Devam etmek"}, {"en": "Control", "tr": "Kontrol etmek"},
    {"en": "Create", "tr": "Yaratmak"}, {"en": "Cry", "tr": "Ağlamak"}, {"en": "Decide", "tr": "Karar vermek"}, {"en": "Describe", "tr": "Tanımlamak"},
    {"en": "Design", "tr": "Tasarlamak"}, {"en": "Destroy", "tr": "Yok etmek"}, {"en": "Discover", "tr": "Keşfetmek"}, {"en": "Discuss", "tr": "Tartışmak"},
    {"en": "Divide", "tr": "Bölmek"}, {"en": "Dream", "tr": "Rüya görmek/Hayal kurmak"}, {"en": "Earn", "tr": "Kazanmak (para vb.)"}, {"en": "Enjoy", "tr": "Keyif almak"},
    {"en": "Enter", "tr": "Girmek"}, {"en": "Explain", "tr": "Açıklamak"}, {"en": "Fall", "tr": "Düşmek"}, {"en": "Fill", "tr": "Doldurmak"},
    {"en": "Follow", "tr": "Takip etmek"}, {"en": "Grow", "tr": "Büyümek"}, {"en": "Guess", "tr": "Tahmin etmek"}, {"en": "Happen", "tr": "Olmak/Meydana gelmek"},
    {"en": "Hate", "tr": "Nefret etmek"}, {"en": "Hear", "tr": "Duymak"}, {"en": "Hide", "tr": "Gizlemek"}, {"en": "Hope", "tr": "Umut etmek"},
    {"en": "Imagine", "tr": "Hayal etmek"}, {"en": "Improve", "tr": "Geliştirmek"}, {"en": "Include", "tr": "Dahil etmek"}, {"en": "Increase", "tr": "Artırmak"},
    {"en": "Inform", "tr": "Bilgilendirmek"}, {"en": "Invite", "tr": "Davet etmek"}, {"en": "Join", "tr": "Katılmak"}, {"en": "Kill", "tr": "Öldürmek"},
    {"en": "Know", "tr": "Bilmek"}, {"en": "Laugh", "tr": "Gülmek"}, {"en": "Lead", "tr": "Liderlik etmek"}, {"en": "Leave", "tr": "Ayrılmak/Terk etmek"},
    {"en": "Let", "tr": "İzin vermek"}, {"en": "Lie", "tr": "Yalan söylemek/Uzanmak"}, {"en": "Lift", "tr": "Kaldırmak"}, {"en": "Lose", "tr": "Kaybetmek"},
    {"en": "Make", "tr": "Yapmak"}, {"en": "Manage", "tr": "Yönetmek"}, {"en": "Mean", "tr": "Anlamına gelmek"}, {"en": "Meet", "tr": "Buluşmak/Tanışmak"},
    {"en": "Move", "tr": "Hareket etmek"}, {"en": "Need", "tr": "İhtiyaç duymak"}, {"en": "Notice", "tr": "Fark etmek"}, {"en": "Offer", "tr": "Teklif etmek"},
    {"en": "Order", "tr": "Sipariş vermek/Emretmek"}, {"en": "Pass", "tr": "Geçmek"}, {"en": "Pick", "tr": "Seçmek/Toplamak"}, {"en": "Plan", "tr": "Planlamak"},
    {"en": "Prepare", "tr": "Hazırlamak"}, {"en": "Promise", "tr": "Söz vermek"}, {"en": "Protect", "tr": "Korumak"}, {"en": "Push", "tr": "İtmek"},
    {"en": "Pull", "tr": "Çekmek"}, {"en": "Reach", "tr": "Ulaşmak"}, {"en": "Refuse", "tr": "Reddetmek"}, {"en": "Relax", "tr": "Rahatlamak"},
    {"en": "Remove", "tr": "Kaldırmak"}, {"en": "Repeat", "tr": "Tekrar etmek"}, {"en": "Reply", "tr": "Cevap vermek"}, {"en": "Save", "tr": "Kaydetmek/Kurtarmak"},
    {"en": "Search", "tr": "Aramak"}, {"en": "Seem", "tr": "Görünmek"}, {"en": "Sell", "tr": "Satmak"}, {"en": "Share", "tr": "Paylaşmak"},
    {"en": "Shout", "tr": "Bağırmak"}, {"en": "Sit", "tr": "Oturmak"}, {"en": "Smile", "tr": "Gülümsemek"}, {"en": "Spend", "tr": "Harcamak"},
    {"en": "Stand", "tr": "Ayakta durmak"}, {"en": "Stay", "tr": "Kalmak"}, {"en": "Study", "tr": "Ders çalışmak"}, {"en": "Suggest", "tr": "Öneride bulunmak"},
    {"en": "Support", "tr": "Desteklemek"}, {"en": "Surprise", "tr": "Şaşırtmak"}, {"en": "Talk", "tr": "Konuşmak"}, {"en": "Tell", "tr": "Anlatmak/Söylemek"},
    {"en": "Think", "tr": "Düşünmek"}, {"en": "Throw", "tr": "Atmak"}, {"en": "Understand", "tr": "Anlamak"}, {"en": "Use", "tr": "Kullanmak"},
    {"en": "Visit", "tr": "Ziyaret etmek"}, {"en": "Wait", "tr": "Beklemek"}, {"en": "Wake", "tr": "Uyanmak"}, {"en": "Want", "tr": "İstemek"},
    {"en": "Warn", "tr": "Uyarılmak"}, {"en": "Wash", "tr": "Yıkamak"}, {"en": "Wear", "tr": "Giyinmek"}, {"en": "Win", "tr": "Kazanmak"},
    {"en": "Wish", "tr": "Dilemek"}, {"en": "Work", "tr": "Çalışmak"}, {"en": "Worry", "tr": "Endişelenmek"}, {"en": "Adult", "tr": "Yetişkin"},
    {"en": "Air", "tr": "Hava"}, {"en": "Area", "tr": "Alan"}, {"en": "Army", "tr": "Ordu"}, {"en": "Art", "tr": "Sanat"},
    {"en": "Attack", "tr": "Saldırı"}, {"en": "Baby", "tr": "Bebek"}, {"en": "Back", "tr": "Geri/Arka"}, {"en": "Ball", "tr": "Top"},
    {"en": "Bank", "tr": "Banka"}, {"en": "Bar", "tr": "Bar/Çubuk"}, {"en": "Base", "tr": "Temel/Üs"}, {"en": "Beat", "tr": "Vurmak/Yenmek"},
    {"en": "Beauty", "tr": "Güzellik"}, {"en": "Bed", "tr": "Yatak"}, {"en": "Beginner", "tr": "Yeni başlayan"}, {"en": "Bell", "tr": "Zil/Çan"},
    {"en": "Bill", "tr": "Fatura"}, {"en": "Bird", "tr": "Kuş"}, {"en": "Birth", "tr": "Doğum"}, {"en": "Blood", "tr": "Kan"},
    {"en": "Board", "tr": "Tahta/Kurul"}, {"en": "Boat", "tr": "Tekne"}, {"en": "Body", "tr": "Vücut"}, {"en": "Bone", "tr": "Kemik"},
    {"en": "Bottom", "tr": "Alt/Dip"}, {"en": "Box", "tr": "Kutu"}, {"en": "Boy", "tr": "Erkek çocuk"}, {"en": "Brain", "tr": "Beyin"},
    {"en": "Branch", "tr": "Dal/Şube"}, {"en": "Bridge", "tr": "Köprü"}, {"en": "Brother", "tr": "Erkek kardeş"}, {"en": "Building", "tr": "Bina"},
    {"en": "Burn", "tr": "Yanmak"}, {"en": "Business", "tr": "İş/Ticaret"}, {"en": "Button", "tr": "Düğme"}, {"en": "Cake", "tr": "Kek/Pasta"},
    {"en": "Camera", "tr": "Kamera"}, {"en": "Camp", "tr": "Kamp"}, {"en": "Card", "tr": "Kart"}, {"en": "Case", "tr": "Durum/Kasa"},
    {"en": "Cause", "tr": "Neden/Sebep"}, {"en": "Center", "tr": "Merkez"}, {"en": "Century", "tr": "Yüzyıl"}, {"en": "Chance", "tr": "Şans"},
    {"en": "Character", "tr": "Karakter"}, {"en": "Charge", "tr": "Ücret/Yükleme"}, {"en": "Check", "tr": "Kontrol"}, {"en": "Child", "tr": "Çocuk"},
    {"en": "Choice", "tr": "Seçim"}, {"en": "Church", "tr": "Kilise"}, {"en": "Class", "tr": "Sınıf"}, {"en": "Clock", "tr": "Saat"},
    {"en": "Clothes", "tr": "Kıyafetler"}, {"en": "Cloud", "tr": "Bulut"}, {"en": "Club", "tr": "Kulüp"}, {"en": "Coat", "tr": "Palto/Ceket"},
    {"en": "Coffee", "tr": "Kahve"}, {"en": "Color", "tr": "Renk"}, {"en": "Company", "tr": "Şirket"}, {"en": "Condition", "tr": "Durum/Koşul"},
    {"en": "Control", "tr": "Kontrol"}, {"en": "Corner", "tr": "Köşe"}, {"en": "Country", "tr": "Ülke"}, {"en": "Course", "tr": "Kurs/Ders"},
    {"en": "Court", "tr": "Mahkeme/Kort"}, {"en": "Cover", "tr": "Kapak/Örtü"}, {"en": "Cow", "tr": "İnek"}, {"en": "Crowd", "tr": "Kalabalık"},
    {"en": "Cup", "tr": "Fincan/Kupa"}, {"en": "Current", "tr": "Güncel/Akım"}, {"en": "Custom", "tr": "Gelenek/Özel"}, {"en": "Cut", "tr": "Kesmek"},
    {"en": "Danger", "tr": "Tehlike"}, {"en": "Daughter", "tr": "Kız evlat"}, {"en": "Death", "tr": "Ölüm"}, {"en": "Decision", "tr": "Karar"},
    {"en": "Degree", "tr": "Derece"}, {"en": "Design", "tr": "Tasarım"}, {"en": "Desk", "tr": "Sıra/Masa"}, {"en": "Detail", "tr": "Detay"},
    {"en": "Difference", "tr": "Fark"}, {"en": "Direction", "tr": "Yön"}, {"en": "Distance", "tr": "Mesafe"}, {"en": "Doctor", "tr": "Doktor"},
    {"en": "Dream", "tr": "Rüya"}, {"en": "Dress", "tr": "Elbise"}, {"en": "Driver", "tr": "Sürücü"}, {"en": "Drop", "tr": "Düşürmek/Damla"},
    {"en": "Duty", "tr": "Görev"}, {"en": "Earth", "tr": "Dünya/Toprak"}, {"en": "East", "tr": "Doğu"}, {"en": "Edge", "tr": "Kenar"},
    {"en": "Education", "tr": "Eğitim"}, {"en": "Effect", "tr": "Etki"}, {"en": "Effort", "tr": "Çaba"}, {"en": "End", "tr": "Son"},
    {"en": "Enemy", "tr": "Düşman"}, {"en": "Energy", "tr": "Enerji"}, {"en": "Engine", "tr": "Motor"}, {"en": "Environment", "tr": "Çevre"},
    {"en": "Event", "tr": "Etkinlik"}, {"en": "Example", "tr": "Örnek"}, {"en": "Experience", "tr": "Deneyim"}, {"en": "Eye", "tr": "Göz"},
    {"en": "Face", "tr": "Yüz"}, {"en": "Fact", "tr": "Gerçek"}, {"en": "Family", "tr": "Aile"}, {"en": "Farm", "tr": "Çiftlik"},
    {"en": "Father", "tr": "Baba"}, {"en": "Fear", "tr": "Korku"}, {"en": "Field", "tr": "Alan/Tarla"}, {"en": "Fight", "tr": "Dövüş"},
    {"en": "Finger", "tr": "Parmak"}, {"en": "Fire", "tr": "Ateş"}, {"en": "Floor", "tr": "Yer/Kat"}, {"en": "Flower", "tr": "Çiçek"},
    {"en": "Food", "tr": "Yemek"}, {"en": "Foot", "tr": "Ayak"}, {"en": "Force", "tr": "Güç/Zorlamak"}, {"en": "Forest", "tr": "Orman"},
    {"en": "Form", "tr": "Form/Şekil"}, {"en": "Future", "tr": "Gelecek"}, {"en": "Game", "tr": "Oyun"}, {"en": "Garden", "tr": "Bahçe"},
    {"en": "Gas", "tr": "Gaz/Benzin"}, {"en": "General", "tr": "Genel"}, {"en": "Gift", "tr": "Hediye"}, {"en": "Girl", "tr": "Kız çocuk"},
    {"en": "Glass", "tr": "Bardak/Cam"}, {"en": "Gold", "tr": "Altın"}, {"en": "Government", "tr": "Hükümet"}, {"en": "Grass", "tr": "Çimen"},
    // --- GRUP 5 & 6: SOSYAL, TEKNİK VE DİĞER (361-600) ---
    {"en": "Great", "tr": "Harika"}, {"en": "Green", "tr": "Yeşil"}, {"en": "Ground", "tr": "Yer/Zemin"}, {"en": "Group", "tr": "Grup"},
    {"en": "Growth", "tr": "Büyüme"}, {"en": "Guard", "tr": "Gardiyan/Korumak"}, {"en": "Guide", "tr": "Rehber"}, {"en": "Gun", "tr": "Silah"},
    {"en": "Hair", "tr": "Saç"}, {"en": "Half", "tr": "Yarım"}, {"en": "Hall", "tr": "Hol/Salon"}, {"en": "Hand", "tr": "El"},
    {"en": "Head", "tr": "Kafa/Baş"}, {"en": "Health", "tr": "Sağlık"}, {"en": "Heart", "tr": "Kalp"}, {"en": "Heat", "tr": "Isı"},
    {"en": "Heavy", "tr": "Ağır"}, {"en": "High", "tr": "Yüksek"}, {"en": "History", "tr": "Tarih"}, {"en": "Hole", "tr": "Delik"},
    {"en": "Holiday", "tr": "Tatil"}, {"en": "Home", "tr": "Ev"}, {"en": "Hope", "tr": "Umut"}, {"en": "Horse", "tr": "At"},
    {"en": "Hospital", "tr": "Hastane"}, {"en": "Hotel", "tr": "Otel"}, {"en": "Hour", "tr": "Saat (süre)"}, {"en": "Human", "tr": "İnsan"},
    {"en": "Idea", "tr": "Fikir"}, {"en": "Image", "tr": "Görüntü"}, {"en": "Important", "tr": "Önemli"}, {"en": "Inside", "tr": "İçerisi"},
    {"en": "Island", "tr": "Ada"}, {"en": "Job", "tr": "İş"}, {"en": "Journey", "tr": "Yolculuk"}, {"en": "Juice", "tr": "Meyve suyu"},
    {"en": "Kind", "tr": "Tür/Nazik"}, {"en": "King", "tr": "Kral"}, {"en": "Kitchen", "tr": "Mutfak"}, {"en": "Lady", "tr": "Hanımefendi"},
    {"en": "Land", "tr": "Arazi/Kara"}, {"en": "Language", "tr": "Dil"}, {"en": "Last", "tr": "Son"}, {"en": "Law", "tr": "Kanun/Hukuk"},
    {"en": "Left", "tr": "Sol"}, {"en": "Leg", "tr": "Bacak"}, {"en": "Letter", "tr": "Mektup/Harf"}, {"en": "Level", "tr": "Seviye"},
    {"en": "Light", "tr": "Işık/Hafif"}, {"en": "Line", "tr": "Hat/Çizgi"}, {"en": "List", "tr": "Liste"}, {"en": "Local", "tr": "Yerel"},
    {"en": "Lock", "tr": "Kilit"}, {"en": "Long", "tr": "Uzun"}, {"en": "Low", "tr": "Düşük"}, {"en": "Main", "tr": "Ana/Temel"},
    {"en": "Map", "tr": "Harita"}, {"en": "Mark", "tr": "İşaret/Not"}, {"en": "Market", "tr": "Market"}, {"en": "Marriage", "tr": "Evlilik"},
    {"en": "Material", "tr": "Malzeme"}, {"en": "Medicine", "tr": "İlaç/Tıp"}, {"en": "Member", "tr": "Üye"}, {"en": "Memory", "tr": "Hafıza"},
    {"en": "Message", "tr": "Mesaj"}, {"en": "Metal", "tr": "Metal"}, {"en": "Middle", "tr": "Orta"}, {"en": "Mind", "tr": "Zihin"},
    {"en": "Minute", "tr": "Dakika"}, {"en": "Mirror", "tr": "Ayna"}, {"en": "Mistake", "tr": "Hata"}, {"en": "Modern", "tr": "Modern"},
    {"en": "Mountain", "tr": "Dağ"}, {"en": "Mouth", "tr": "Ağız"}, {"en": "Music", "tr": "Müzik"}, {"en": "Nation", "tr": "Ulus"},
    {"en": "Nature", "tr": "Doğa"}, {"en": "Near", "tr": "Yakın"}, {"en": "Neck", "tr": "Boyun"}, {"en": "Neighbor", "tr": "Komşu"},
    {"en": "Network", "tr": "Ağ"}, {"en": "News", "tr": "Haberler"}, {"en": "Noisy", "tr": "Gürültülü"}, {"en": "North", "tr": "Kuzey"},
    {"en": "Nose", "tr": "Burun"}, {"en": "Note", "tr": "Not"}, {"en": "Number", "tr": "Sayı"}, {"en": "Object", "tr": "Nesne"},
    {"en": "Oil", "tr": "Yağ"}, {"en": "Option", "tr": "Seçenek"}, {"en": "Owner", "tr": "Sahip"}, {"en": "Page", "tr": "Sayfa"},
    {"en": "Pain", "tr": "Aacı"}, {"en": "Paper", "tr": "Kağıt"}, {"en": "Parent", "tr": "Ebeveyn"}, {"en": "Park", "tr": "Park"},
    {"en": "Part", "tr": "Parça"}, {"en": "Partner", "tr": "Ortak"}, {"en": "Party", "tr": "Parti"}, {"en": "Past", "tr": "Geçmiş"},
    {"en": "Path", "tr": "Yol/Patika"}, {"en": "Peace", "tr": "Barış"}, {"en": "Person", "tr": "Kişi"}, {"en": "Phone", "tr": "Telefon"},
    {"en": "Picture", "tr": "Resim"}, {"en": "Piece", "tr": "Parça"}, {"en": "Place", "tr": "Yer"}, {"en": "Plant", "tr": "Bitki"},
    {"en": "Plastic", "tr": "Plastik"}, {"en": "Plate", "tr": "Tabak"}, {"en": "Point", "tr": "Nokta"}, {"en": "Police", "tr": "Polis"},
    {"en": "Position", "tr": "Pozisyon"}, {"en": "Possible", "tr": "Mümkün"}, {"en": "Power", "tr": "Güç"}, {"en": "Present", "tr": "Hediye/Mevcut"},
    {"en": "President", "tr": "Başkan"}, {"en": "Private", "tr": "Özel"}, {"en": "Problem", "tr": "Problem"}, {"en": "Process", "tr": "Süreç"},
    {"en": "Public", "tr": "Halk/Kamu"}, {"en": "Purpose", "tr": "Amaç"}, {"en": "Quality", "tr": "Kalite"}, {"en": "Question", "tr": "Soru"},
    {"en": "Quick", "tr": "Hızlı"}, {"en": "Quiet", "tr": "Sessiz"}, {"en": "Radio", "tr": "Radyo"}, {"en": "Rain", "tr": "Yağmur"},
    {"en": "Reason", "tr": "Sebep"}, {"en": "Record", "tr": "Kayıt"}, {"en": "Region", "tr": "Bölge"}, {"en": "Relation", "tr": "İlişki"},
    {"en": "Report", "tr": "Rapor"}, {"en": "Result", "tr": "Sonuç"}, {"en": "Rich", "tr": "Zengin"}, {"en": "Right", "tr": "Doğru/Sağ"},
    {"en": "Ring", "tr": "Yüzük/Çalmak"}, {"en": "Rise", "tr": "Yükselmek"}, {"en": "River", "tr": "Nehir"}, {"en": "Road", "tr": "Yol"},
    {"en": "Rock", "tr": "Kaya"}, {"en": "Roof", "tr": "Çatı"}, {"en": "Room", "tr": "Oda"}, {"en": "Safe", "tr": "Güvenli"},
    {"en": "Salt", "tr": "Tuz"}, {"en": "Same", "tr": "Aynı"}, {"en": "Sand", "tr": "Kum"}, {"en": "Scene", "tr": "Sahne"},
    {"en": "Science", "tr": "Bilim"}, {"en": "Sea", "tr": "Deniz"}, {"en": "Season", "tr": "Mevsim"}, {"en": "Seat", "tr": "Koltuk"},
    {"en": "Second", "tr": "Saniye/İkinci"}, {"en": "Secret", "tr": "Sır"}, {"en": "Section", "tr": "Bölüm"}, {"en": "Self", "tr": "Kendi"},
    {"en": "Sentence", "tr": "Cümle"}, {"en": "Service", "tr": "Servis"}, {"en": "Shadow", "tr": "Gölge"}, {"en": "Shape", "tr": "Şekil"},
    {"en": "Ship", "tr": "Gemi"}, {"en": "Shirt", "tr": "Gömlek"}, {"en": "Shoes", "tr": "Ayakkabı"}, {"en": "Shop", "tr": "Dükkan"},
    {"en": "Short", "tr": "Kısa"}, {"en": "Side", "tr": "Taraf"}, {"en": "Sign", "tr": "İşaret"}, {"en": "Silver", "tr": "Gümüş"},
    {"en": "Simple", "tr": "Basit"}, {"en": "Single", "tr": "Tek"}, {"en": "Sister", "tr": "Kız kardeş"}, {"en": "Skin", "tr": "Cilt"},
    {"en": "Sky", "tr": "Gökyüzü"}, {"en": "Snow", "tr": "Kar"}, {"en": "Social", "tr": "Sosyal"}, {"en": "Soft", "tr": "Yumuşak"},
    {"en": "Soil", "tr": "Toprak"}, {"en": "Son", "tr": "Erkek evlat"}, {"en": "Song", "tr": "Şarkı"}, {"en": "Sound", "tr": "Ses"},
    {"en": "South", "tr": "Güney"}, {"en": "Space", "tr": "Uzay/Alan"}, {"en": "Special", "tr": "Özel"}, {"en": "Sport", "tr": "Spor"},
    {"en": "Spring", "tr": "Bahar"}, {"en": "Square", "tr": "Kare"}, {"en": "Stage", "tr": "Aşama/Sahne"}, {"en": "Star", "tr": "Yıldız"},
    {"en": "Station", "tr": "İstasyon"}, {"en": "Steam", "tr": "Buhar"}, {"en": "Step", "tr": "Adım"}, {"en": "Stick", "tr": "Sopa"},
    {"en": "Still", "tr": "Hala"}, {"en": "Stone", "tr": "Taş"}, {"en": "Story", "tr": "Hikaye"}, {"en": "Street", "tr": "Sokak"},
    {"en": "Strong", "tr": "Güçlü"}, {"en": "Student", "tr": "Öğrenci"}, {"en": "Subject", "tr": "Konu"}, {"en": "Sugar", "tr": "Şeker"},
    {"en": "Summer", "tr": "Yaz"}, {"en": "Support", "tr": "Destek"}, {"en": "System", "tr": "Sistem"}, {"en": "Tall", "tr": "Uzun (boy)"},
    {"en": "Taste", "tr": "Tat"}, {"en": "Tax", "tr": "Vergi"}, {"en": "Tea", "tr": "Çay"}, {"en": "Teacher", "tr": "Öğretmen"},
    {"en": "Team", "tr": "Takım"}, {"en": "Telephone", "tr": "Telefon"}, {"en": "Television", "tr": "Televizyon"}, {"en": "Temperature", "tr": "Sıcaklık"},
    {"en": "Test", "tr": "Test"}, {"en": "Thin", "tr": "İnce"}, {"en": "Thing", "tr": "Şey"}, {"en": "Ticket", "tr": "Bilet"},
    {"en": "Top", "tr": "Üst"}, {"en": "Total", "tr": "Toplam"}, {"en": "Touch", "tr": "Dokunmak"}, {"en": "Town", "tr": "Kasaba"},
    {"en": "Trade", "tr": "Ticaret"}, {"en": "Train", "tr": "Tren"}, {"en": "Travel", "tr": "Seyahat"}, {"en": "True", "tr": "Doğru"},
    {"en": "Type", "tr": "Tip/Tür"}, {"en": "Under", "tr": "Altında"}, {"en": "Unit", "tr": "Birim"}, {"en": "Until", "tr": "Kadar"},
    {"en": "Up", "tr": "Yukarı"}, {"en": "Value", "tr": "Değer"}, {"en": "View", "tr": "Görünüm"}, {"en": "Village", "tr": "Köy"},
    {"en": "Voice", "tr": "Ses"}, {"en": "Wall", "tr": "Duvar"}, {"en": "War", "tr": "Savaş"}, {"en": "Warm", "tr": "Ilık"},
    {"en": "Way", "tr": "Yol"}, {"en": "Weather", "tr": "Hava durumu"}, {"en": "Weight", "tr": "Ağırlık"}, {"en": "West", "tr": "Batı"},
    {"en": "Wheel", "tr": "Tekerlek"}, {"en": "White", "tr": "Beyaz"}, {"en": "Wide", "tr": "Geniş"}, {"en": "Wife", "tr": "Eş (kadın)"},
    {"en": "Wind", "tr": "Rüzgar"}, {"en": "Wine", "tr": "Şarap"}, {"en": "Winter", "tr": "Kış"}, {"en": "Woman", "tr": "Kadın"},
    {"en": "Wood", "tr": "Odun"}, {"en": "Word", "tr": "Kelime"}, {"en": "Yard", "tr": "Bahçe/Avlu"}, {"en": "Young", "tr": "Genç"},
  ];
}